"""
=============================================================================
  MANA AI — Automated System Maintenance & Cleanup Engine
  Purpose : Auto-prune old log files, rotate session tokens, truncate
            unbounded SDK logs, clean __pycache__, and prevent disk bloat
            across backend, engine, and paper observer.
=============================================================================
"""

import os
import json
import shutil
import time
import pathlib
import logging
from typing import Dict, Any, List

logger = logging.getLogger("maintenance")

ROOT_DIR = pathlib.Path(__file__).resolve().parents[1]  # trading-system/
LOGS_DIR = ROOT_DIR / "logs"
CONFIG_DIR = ROOT_DIR / "config"
SESSIONS_FILE = CONFIG_DIR / "sessions.json"

# ---------------------------------------------------------------------------
# Fyers SDK log files — these have NO built-in rotation and grow unbounded.
# Truncate them when they exceed the threshold below.
# ---------------------------------------------------------------------------
_SDK_LOG_FILES = ["fyersRequests.log", "fyersDataSocket.log"]
_SDK_LOG_MAX_MB = 10  # truncate if larger than 10 MB


def cleanup_old_logs(max_age_days: int = 7, max_total_mb: float = 30.0) -> Dict[str, Any]:
    """
    Automatically clean up stale log files older than `max_age_days`
    and ensure total log directory size does not exceed `max_total_mb`.
    """
    cleaned_files = []
    freed_bytes = 0
    now = time.time()
    cutoff_time = now - (max_age_days * 86400)
    
    # 1. Clean old dated log files in logs/
    if LOGS_DIR.exists():
        for log_file in list(LOGS_DIR.iterdir()):
            if not log_file.is_file():
                continue
            if log_file.name == ".gitkeep":
                continue
            
            # Keep active primary logs (engine.log, engine.log.1, etc.)
            if log_file.name.startswith("engine.log"):
                continue
                
            try:
                st = log_file.stat()
                if st.st_mtime < cutoff_time:
                    sz = st.st_size
                    log_file.unlink()
                    cleaned_files.append(log_file.name)
                    freed_bytes += sz
            except Exception as e:
                logger.debug("Failed to remove log file %s: %s", log_file.name, e)
                
    # 2. Clean old fyersApi backup logs in root if exceeding 3 backups
    for f in ROOT_DIR.glob("fyersApi.log.*"):
        try:
            suffix = f.name.replace("fyersApi.log.", "")
            if suffix.isdigit() and int(suffix) > 3:
                sz = f.stat().st_size
                f.unlink()
                cleaned_files.append(f.name)
                freed_bytes += sz
        except Exception:
            pass

    freed_mb = round(freed_bytes / (1024 * 1024), 2)
    return {
        "status": "success",
        "cleaned_count": len(cleaned_files),
        "freed_mb": freed_mb,
        "files_removed": cleaned_files[:10]
    }


def truncate_sdk_logs(max_mb: float = _SDK_LOG_MAX_MB) -> Dict[str, Any]:
    """Truncate Fyers SDK log files that have no built-in rotation.

    The Fyers Python SDK writes to ``fyersRequests.log`` and
    ``fyersDataSocket.log`` without any size cap.  Left unchecked these
    can grow past 100 MB in a single trading session.  This function
    truncates them to zero when they exceed *max_mb*, keeping the file
    handle valid for any process still writing to it.
    """
    truncated: List[str] = []
    freed_bytes = 0
    max_bytes = int(max_mb * 1024 * 1024)

    for name in _SDK_LOG_FILES:
        path = ROOT_DIR / name
        if not path.is_file():
            continue
        try:
            size = path.stat().st_size
            if size > max_bytes:
                # Truncate in-place — keeps the file handle valid even if
                # the Fyers SDK still has it open.
                with open(path, "r+b") as fh:
                    fh.truncate(0)
                truncated.append(name)
                freed_bytes += size
                logger.info(
                    "Truncated %s: was %.1f MB (limit: %.0f MB)",
                    name, size / (1024 * 1024), max_mb,
                )
        except Exception as exc:
            # File may be locked on Windows — log and move on.
            logger.debug("Could not truncate %s: %s", name, exc)

    return {
        "truncated": truncated,
        "freed_mb": round(freed_bytes / (1024 * 1024), 2),
    }


def cleanup_pycache() -> Dict[str, Any]:
    """Remove all ``__pycache__`` directories under the trading-system root.

    These are auto-regenerated by Python on the next import and can
    accumulate hundreds of MB of stale ``.pyc`` files over time.
    """
    removed = 0
    freed_bytes = 0
    for dirpath, dirnames, _filenames in os.walk(ROOT_DIR, topdown=False):
        # Skip venv and .git
        if "venv" in dirpath or ".git" in dirpath:
            continue
        for d in dirnames:
            if d == "__pycache__":
                cache_path = pathlib.Path(dirpath) / d
                try:
                    sz = sum(
                        f.stat().st_size for f in cache_path.rglob("*") if f.is_file()
                    )
                    shutil.rmtree(cache_path, ignore_errors=True)
                    removed += 1
                    freed_bytes += sz
                except Exception:
                    pass
    return {"removed_dirs": removed, "freed_mb": round(freed_bytes / (1024 * 1024), 2)}


def cleanup_bak_files() -> Dict[str, Any]:
    """Remove stale ``.bak`` and ``.restored-backup`` files in ``data/`` and ``models/``."""
    cleaned: List[str] = []
    freed_bytes = 0
    scan_dirs = [ROOT_DIR / "data", ROOT_DIR / "models"]
    patterns = ["*.bak", "*.restored-backup"]

    for scan_dir in scan_dirs:
        if not scan_dir.is_dir():
            continue
        for pattern in patterns:
            for f in scan_dir.glob(pattern):
                try:
                    sz = f.stat().st_size
                    f.unlink()
                    cleaned.append(str(f.relative_to(ROOT_DIR)))
                    freed_bytes += sz
                except Exception:
                    pass

    return {"cleaned": cleaned, "freed_mb": round(freed_bytes / (1024 * 1024), 2)}


def cleanup_sessions(max_active: int = 20) -> Dict[str, Any]:
    """
    Purge expired sessions and cap total active sessions at `max_active`.
    """
    if not SESSIONS_FILE.exists():
        return {"status": "no_file", "purged": 0}
        
    try:
        with open(SESSIONS_FILE, "r", encoding="utf-8") as f:
            sessions = json.load(f)
            
        now = time.time()
        # Keep non-expired
        valid = {tok: s for tok, s in sessions.items() if s.get("expires_at", 0) > now}
        
        # If still more than max_active, keep the newest ones
        if len(valid) > max_active:
            sorted_tokens = sorted(valid.items(), key=lambda item: item[1].get("created_at", 0), reverse=True)
            valid = dict(sorted_tokens[:max_active])
            
        purged_count = len(sessions) - len(valid)
        
        if purged_count > 0:
            import tempfile
            fd, tmp_path = tempfile.mkstemp(dir=CONFIG_DIR, prefix="sessions_tmp_", suffix=".json")
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                json.dump(valid, f, indent=2)
            os.replace(tmp_path, SESSIONS_FILE)
            
        return {
            "status": "success",
            "purged_count": purged_count,
            "remaining_count": len(valid)
        }
    except Exception as exc:
        logger.error("Failed to cleanup sessions: %s", exc)
        return {"status": "error", "error": str(exc)}


def run_system_maintenance() -> Dict[str, Any]:
    """Run all routine maintenance tasks on startup."""
    log_res = cleanup_old_logs()
    sdk_res = truncate_sdk_logs()
    cache_res = cleanup_pycache()
    bak_res = cleanup_bak_files()
    sess_res = cleanup_sessions()

    total_freed = (
        log_res.get("freed_mb", 0)
        + sdk_res.get("freed_mb", 0)
        + cache_res.get("freed_mb", 0)
        + bak_res.get("freed_mb", 0)
    )

    logger.info(
        "System maintenance complete — freed %.1f MB total "
        "(logs: %.1f, sdk: %.1f, pycache: %.1f, bak: %.1f, sessions purged: %s)",
        total_freed,
        log_res.get("freed_mb", 0),
        sdk_res.get("freed_mb", 0),
        cache_res.get("freed_mb", 0),
        bak_res.get("freed_mb", 0),
        sess_res.get("purged_count", 0),
    )

    return {
        "logs": log_res,
        "sdk_logs": sdk_res,
        "pycache": cache_res,
        "bak_files": bak_res,
        "sessions": sess_res,
        "total_freed_mb": round(total_freed, 2),
    }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    res = run_system_maintenance()
    print("Maintenance summary:")
    print(f"  Logs cleaned: {res['logs']['cleaned_count']} files ({res['logs']['freed_mb']} MB freed)")
    print(f"  SDK logs truncated: {', '.join(res['sdk_logs']['truncated']) or 'none'} ({res['sdk_logs']['freed_mb']} MB freed)")
    print(f"  __pycache__ dirs removed: {res['pycache']['removed_dirs']} ({res['pycache']['freed_mb']} MB freed)")
    print(f"  .bak files cleaned: {len(res['bak_files']['cleaned'])} ({res['bak_files']['freed_mb']} MB freed)")
    print(f"  Sessions purged: {res['sessions'].get('purged_count', 0)}")
    print(f"  Total freed: {res['total_freed_mb']} MB")
