"""The backtest must charge the costs an option buyer actually pays (2026-09-10).

`run_intraday_backtest()` is the engine `grid_search.py`, `/api/backtest` and
every tuning script use. Measured against the first paper session filled at
real quoted prices, its friction model was wrong in two independent ways that
partially cancelled -- so neither showed up in the headline numbers:

1. **Wrong basis.** `slippage_bps` is applied to the UNDERLYING (`spot x bps`)
   and scaled by delta. The real cost of entering and exiting an option is its
   bid/ask spread, which scales with the PREMIUM. Those grow differently, so
   the error changes sign between NIFTY and BANKNIFTY rather than being a
   constant bias that could be corrected for afterwards.

2. **No theta at all.** The word did not appear in the file. For an option
   BUYER theta is the dominant cost -- observed -7.35 to -14.0 per day against
   premiums of 81 to 490.

Net effect on a NIFTY ATM contract: a flat Rs.4.22/unit regardless of hold
time, against a real Rs.0.64 at 30 minutes rising past Rs.4.22 only beyond
~6.6 hours. Short holds were over-penalised up to 6.6x, full-day holds
under-penalised.

Validated against the four real Day 6 trades:

    old model  Rs.21.82  (405% of reality)
    new model  Rs. 5.34  ( 99% of reality)

Note this engine had **no coverage in the active CI suite** -- its only tests
live in the legacy `trading-system/tests/`, which CI does not collect.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from backtesting_engine.run import (
    OPTION_COST_PROFILES,
    option_cost_profile,
    run_intraday_backtest,
)


def _frame(n: int = 120, seed: int = 3) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    close = pd.Series(23_400 + rng.normal(0, 18, n).cumsum())
    idx = pd.date_range("2026-09-10 09:15", periods=n, freq="5min")
    return pd.DataFrame({
        "open": close.shift(1).fillna(close.iloc[0]).to_numpy(),
        "high": (close + np.abs(rng.normal(9, 4, n))).to_numpy(),
        "low": (close - np.abs(rng.normal(9, 4, n))).to_numpy(),
        "close": close.to_numpy(),
        "volume": rng.integers(50_000, 250_000, n).astype(float),
    }, index=idx)


def _signals(df: pd.DataFrame) -> pd.Series:
    s = pd.Series(0, index=df.index, dtype=int)
    s.iloc[10] = 1
    s.iloc[45] = 1
    s.iloc[80] = 1
    return s


# ---------------------------------------------------------------------------
# The costs are actually charged
# ---------------------------------------------------------------------------

def test_costs_are_reported_separately():
    """Their contribution must never be invisible inside the P&L."""
    df = _frame()
    stats = run_intraday_backtest(df, _signals(df))["stats"]
    for key in ("totalSpreadCost", "totalThetaCost", "optionCostsModelled",
                "optionCostParams"):
        assert key in stats, f"{key} missing from stats"
    assert stats["optionCostsModelled"] is True


def test_modelling_costs_reduces_net_pnl():
    df = _frame()
    sigs = _signals(df)
    with_costs = run_intraday_backtest(df, sigs, model_option_costs=True)["stats"]
    without = run_intraday_backtest(df, sigs, model_option_costs=False)["stats"]

    if with_costs["totalTrades"] == 0:
        pytest.skip("no trades generated by this fixture")

    assert with_costs["totalSpreadCost"] > 0
    assert without["totalSpreadCost"] == 0
    assert with_costs["netProfit"] < without["netProfit"], (
        "charging real carrying costs must lower net profit"
    )


def test_disabling_reproduces_the_old_behaviour():
    """An escape hatch for comparing against pre-2026-09-10 numbers."""
    df = _frame()
    stats = run_intraday_backtest(df, _signals(df), model_option_costs=False)["stats"]
    assert stats["optionCostsModelled"] is False
    assert stats["totalSpreadCost"] == 0
    assert stats["totalThetaCost"] == 0


# ---------------------------------------------------------------------------
# Theta must depend on how long the position was held
# ---------------------------------------------------------------------------

def test_theta_scales_with_hold_time():
    """The defining property the old engine lacked entirely: time costs money.

    Same signals, same bars -- only the bar interval changes, so identical
    bar-counts represent longer holds and must decay more.
    """
    df = _frame()
    sigs = _signals(df)
    short = run_intraday_backtest(df, sigs, bar_minutes=1.0)["stats"]
    long_ = run_intraday_backtest(df, sigs, bar_minutes=15.0)["stats"]

    if short["totalTrades"] == 0:
        pytest.skip("no trades generated by this fixture")

    assert long_["totalThetaCost"] > short["totalThetaCost"] * 5, (
        "a 15x longer hold must cost materially more theta"
    )


def test_spread_does_not_scale_with_hold_time():
    """Spread is paid once each way, however long you hold."""
    df = _frame()
    sigs = _signals(df)
    short = run_intraday_backtest(df, sigs, bar_minutes=1.0)["stats"]
    long_ = run_intraday_backtest(df, sigs, bar_minutes=15.0)["stats"]
    if short["totalTrades"] == 0 or short["totalTrades"] != long_["totalTrades"]:
        pytest.skip("trade counts differ; spread comparison not meaningful")
    assert short["totalSpreadCost"] == pytest.approx(long_["totalSpreadCost"], rel=1e-6)


def test_zero_theta_parameter_charges_no_decay():
    df = _frame()
    stats = run_intraday_backtest(df, _signals(df), option_theta_pct_per_day=0.0)["stats"]
    assert stats["totalThetaCost"] == 0


# ---------------------------------------------------------------------------
# Per-index profiles
# ---------------------------------------------------------------------------

def test_banknifty_profile_differs_materially_from_nifty():
    """Using NIFTY parameters for BANKNIFTY misprices it.

    Observed: BANKNIFTY premium is 0.87% of spot with theta ~2.1%/day, against
    NIFTY's 0.40% and 9.7%. Applying one to the other is not a rounding error.
    """
    n = option_cost_profile("NIFTY 23450 CE")
    b = option_cost_profile("BANKNIFTY 56400 PE")
    assert b["option_premium_pct"] > n["option_premium_pct"] * 2
    assert b["option_theta_pct_per_day"] < n["option_theta_pct_per_day"] / 4


def test_profile_lookup_is_by_underlying():
    assert option_cost_profile("BANKNIFTY 56400 PE") == OPTION_COST_PROFILES["BANKNIFTY"]
    assert option_cost_profile("NIFTY 23450 CE") == OPTION_COST_PROFILES["NIFTY"]


@pytest.mark.parametrize("symbol", ["", None, "UNKNOWN-THING"])
def test_unknown_symbols_fall_back_to_nifty(symbol):
    assert option_cost_profile(symbol) == OPTION_COST_PROFILES["NIFTY"]


def test_profiles_are_not_shared_mutable_state():
    p = option_cost_profile("NIFTY")
    p["option_theta_pct_per_day"] = 999
    assert OPTION_COST_PROFILES["NIFTY"]["option_theta_pct_per_day"] != 999


# ---------------------------------------------------------------------------
# Reality check
# ---------------------------------------------------------------------------

def test_model_reproduces_the_observed_day_6_costs():
    """The four real trades of 2026-09-10, priced by the new model.

    Real total was Rs.5.38/unit of friction. Anything within a factor of ~1.5
    is a fair model given three NIFTY observations; the old model charged
    Rs.21.82, i.e. 405%.
    """
    observed = [
        # (symbol, spot, real_premium, real_spread_pct, real_theta_per_day, hours)
        ("NIFTY", 23_423.6, 81.50, 0.25, 7.35, 1.17),
        ("NIFTY", 23_413.8, 77.50, 0.19, 7.58, 0.54),
        ("NIFTY", 23_445.5, 125.45, 0.20, 12.90, 0.83),
        ("BANKNIFTY", 56_429.8, 490.55, 0.35, 10.41, 4.82),
    ]

    real_total = modelled_total = 0.0
    for symbol, spot, premium, spread_pct, theta_day, hours in observed:
        real_total += premium * spread_pct / 100 + theta_day * hours / 24

        p = option_cost_profile(symbol)
        est_premium = spot * p["option_premium_pct"] / 100
        modelled_total += (
            est_premium * p["option_spread_pct"] / 100
            + est_premium * (p["option_theta_pct_per_day"] / 100) * (hours / 24)
        )

    assert real_total == pytest.approx(5.38, abs=0.05)
    ratio = modelled_total / real_total
    assert 0.7 < ratio < 1.5, f"model charges {ratio:.2f}x reality"
